### ISSUE TITLE
Dubious require on calendar.lua

### ISSUE THREAD

**Issue by derivia** [atiladefreitas/dooing#12]
The following code chunk gives an error on start:
```lua
-- from calendar.lua
local vim = require("vim")
```

**Comment by atiladefreitas** [comment]
oh... taking a look

**Comment by derivia** [comment]
Okay, it's fixed, but, why you needed require("vim")?

**Comment by atiladefreitas** [comment]
I got a really annoying local error, there is a fix for that but I've implemented wrongly. Do not remember right now

**Comment by derivia** [comment]
If you can execute everything properly, maybe it's better to use your LSP "ignore options" to handle these.

**Comment by atiladefreitas** [comment]
yeah, I ended up making some big adjustments to my environment, I must have missed something. overall, can I close issue?

**Comment by derivia** [comment]
Feel free to close the issue, i'm preparing a PR with a ui date format enhancement.
