### ISSUE TITLE
Feature request: Ask for confirmation before deleting a not yet complete todo

### ISSUE THREAD

**Issue by a3ylf** [atiladefreitas/dooing#15]
I have deleted some of my yet to be complete todos and this can a bit annoying, since I can't undo it, a confirmation panel would be nice.

**Comment by atiladefreitas** [comment]
you're right, gonna work on that

**Comment by atiladefreitas** [comment]
what you think @a3ylf ?

![image](https://github.com/user-attachments/assets/4988bff2-e5ae-409b-8eb4-cd5111aaf5de)

**Comment by a3ylf** [comment]
This would be great. Thanks!

**Comment by atiladefreitas** [comment]
nice, the last release will be updated in a while

**Comment by atiladefreitas** [comment]
please, update it e tell me how it going

**Comment by a3ylf** [comment]
That's great, thanks.
