### ISSUE TITLE
Feature Request: To-do notes

### ISSUE THREAD

**Issue by andysazima** [atiladefreitas/dooing#27]
I like my to dos to have notes associated with them so I can keep track of progress or thoughts I have during the process of completing the task. This could be a simple description that could show in a floating window to the right, or a whole new buffer. I currently keep to dos in a markdown file with headings and bullets, but I really like your ability to mark things with urgent and important tags (along with a simple UI).

**Comment by atiladefreitas** [comment]
[take a look here](https://github.com/atiladefreitas/dooing/issues/18)

**Comment by andysazima** [comment]
I see you closed the issue. What are your thoughts on this functionality? I think it's distinct from having TODO comments in code. I'm imagining pressing `n` and a floating window shows some notes that are stored for the todo. Like a scratchpad of ideas.

**Comment by atiladefreitas** [comment]
hey buddy, closed the wrong issue, sorry for that.

Add to-do notes is kinda goes against the [TODO Comments plugin](https://github.com/folke/todo-comments.nvim) from Folke.

In these momment I'm thinking about two comments features:

1. A simple integration with Folke's TODO Comments
2. And get inspired by [this guy here](https://www.reddit.com/r/neovim/comments/1h5a5yu/line_notes_add_notes_to_specific_lines/) and adding "hidden" comment in code.

**Comment by andysazima** [comment]
I think we're talking about different things here. I am saying I **don't** just want to leave notes in my code (which folke's plugin is for). I'm suggesting that each todo in the list have an option to add additional info that is stored along with the todo. For instance, I add a new todo in the floating window, assign priority, and then it creates it. Then when I hover over a todo in the list, there's a keyboard shortcut that would open a small floating buffer where you can scratch down some notes for the todo.

**Comment by atiladefreitas** [comment]
oooh now I get it, and I think that is a good idea!
