### ISSUE TITLE
Feature Request: Ability to undo deleting a todo or confirm if you want to delete a todo

### ISSUE THREAD

**Issue by andysazima** [atiladefreitas/dooing#28]
I find that it's too easy to delete todos, and I think one or both of the following would be nice features:

1. Ask me if I want to delete a todo before actually doing so (just hit enter to continue)
2. Allow me to undo deleting a todo

**Comment by atiladefreitas** [comment]
the functionality of confirm to delete an undone todo was actually made, but in recent updated it must be overridden... Currently investigating that

**Comment by atiladefreitas** [comment]
heyy buddy, please [check the latest release](https://github.com/atiladefreitas/dooing/issues/28)

**Comment by andysazima** [comment]
Works exactly how I would expect. Thanks for adding that!
