### ISSUE TITLE
Project Restructuring

### ISSUE THREAD

**Issue by atiladefreitas** [atiladefreitas/dooing#33]
Hello everyone, how are you?

I'm tagging all the contributors here to help me plan this.

In one week the project has grown a lot, especially in the number of new features. In this regard, thank you very much to everyone for your commitment.

I would like to propose a new folder and file structure for the project.

Today the main file (`ui.lua`) has 1998 lines, which is a lot and the tendency is to grow even more.

#### And this is the current structure of the project:

```lua
├── LICENSE
├── lua
│   └── dooing
│       ├── calendar.lua
│       ├── config.lua
│       ├── init.lua
│       ├── state.lua
│       └── ui.lua
├── plugin
│   └── dooing.vim
└── README.md

```

#### This is the new structure I want to propose.

```lua
dooing/
├── lua/
│   └── dooing/
│       ├── init.lua
│       ├── config.lua
│       ├── state.lua
│       └── ui/
│           ├── init.lua       # UI entry point
│           ├── highlights.lua 
│           ├── render.lua     
│           ├── keymaps.lua    
│           ├── windows/
│           │   ├── main.lua
│           │   ├── help.lua
│           │   ├── search.lua
│           │   ├── tags.lua
│           │   ├── calendar.lua
│           │   └── quick_keys.lua
│           └── actions/
│               ├── todo.lua
│               ├── dates.lua
│               ├── time.lua
│               └── io.lua # import and export functionalitie
└── plugin/
    └── dooing.vim
```

Do you think it makes sense? Please let me know.

The main purpose here is quality of life.

@derivia @clementpoiret @a3ylf @KonradMagnusson @buidai123

**Comment by clementpoiret** [comment]
It makes sense to split things out of the main `ui.lua` file yes, I agree. Maybe not very useful, but I really liked this talk, [the life of a file](https://www.youtube.com/watch?v=XpDsk374LDE)

**Comment by derivia** [comment]
I guess keeping ui.lua as a index of the separate windows & other ui-related elements is a great idea. Currently i'm low on time to help with it, and i guess it should be based on your structure opinion.
Also add notes for contributors, to keep the pull requests respecting the project structure.
