### ISSUE TITLE
Built in documentation is missing

### ISSUE THREAD

**Issue by greyblake** [atiladefreitas/dooing#35]
Hi, I just starting exploring your plugin, and I like it! 

I've noticed that it has no built in documentation, which is kind of a standard for every vim plugin.
Would you consider adding?

It's usually a txt file in `doc` folder, here is an example: https://github.com/greyblake/vim-esperanto/blob/master/doc/esperanto.txt, which has a bit weird syntax for links.

If one types `:help dooing` they would expect to see the doc.

Thank you very much!

**Comment by atiladefreitas** [comment]
Hey @greyblake, how have you been?

Really appreciatte that you are enjoying the plugin.

I'm new to the world of neovim plugins and I didn't pay attention to this. I think it makes perfect sense since the plugin is growing in terms of commands and features.

I'll work on it!
