### ISSUE TITLE
Delay when deleting a todo item

### ISSUE THREAD

**Issue by nickvonkaenel** [atiladefreitas/dooing#5]
I'm on Windows and granted Neovim isn't the fastest there but there seems to be a noticeable delay when deleting a todo item. Could there perhaps be some optimization done to whatever is happening there? Even with a single item I can notice the delay.

**Comment by atiladefreitas** [comment]
I'm not able to replicate here... I would love it if you could send a video.

But Dooing works with JSON to store all the to-dos, I assume there may be some bottleneck in reading and updating this JSON in your enviroment. Have you ever experienced any performance problems dealing with JSON in your enviroment?

**Comment by nickvonkaenel** [comment]
I looked into it a bit more. It's not json, as inserting new todos has no delay. I believe it's something to do (no pun intended) with nvim waiting for an additional key after my 'd' key. If I change the shortcut to 'i' for example there is no delay. Not sure if it's a plug-in I have possibly. I could send a video, but not sure how helpful it would be. It's just pressing the d key and then there is a slight delay before the item goes away.

**Comment by nickvonkaenel** [comment]
There is no delay with 'D'

**Comment by atiladefreitas** [comment]
hmm maybe there is an keybind conflict

**Comment by nickvonkaenel** [comment]
I figured out a solution. If you add 'nowait = true' to the keymap then the problem goes away

vim.keymap.set("n", config.options.keymaps.delete_todo, M.delete_todo, { buffer = buf_id, nowait = true })

**Comment by nickvonkaenel** [comment]
it might make sense to add that to all the keymaps

**Comment by atiladefreitas** [comment]
hmm I didn't know about this parameter, I think it might even be useful in other keyboard maps, what you think?

**Comment by atiladefreitas** [comment]
> it might make sense to add that to all the keymaps
totally! I didn't know about this parameter, until now

**Comment by atiladefreitas** [comment]
hey @nickvonkaenel please update your plugin, added nowait in most keymaps.

https://github.com/atiladefreitas/dooing/releases/tag/v1.4.1

**Comment by nickvonkaenel** [comment]
Thanks, that fixed it!
